trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    displayName: Deploy Static Web Application
    inputs:
      app_location: '/'
      output_location: ''
      skip_app_build: true
      azure_static_web_apps_api_token: $(deployment_token)