name: Build and publish the application
on:
  push:
  repository_dispatch:
    types: [ contentful-content-changed ]
jobs:
  job:
    runs-on: ubuntu-latest
    name: Prove that pipeline was triggered
    steps:
      - name: Say hello
        run: echo "Awesome! The job was automatically triggered by a ${{ github.event_name }} event."