name: Build and publish the application

on:
  push:
  repository_dispatch:
    types: [ contentful-content-changed ]

env:
  GATSBY_ENABLE_FEATURE_COMMENTS_SECTION: false

jobs:
  api:
    name: Build and test the API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        working-directory: api
        run: dotnet restore

      - name: Build the API
        working-directory: api
        run: dotnet build --no-restore --no-incremental /WarnAsError

      - name: Run API tests
        working-directory: api
        run: dotnet test --no-restore --no-build

  frontend:
    name: Build and test the Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install packages
        working-directory: frontend
        run: yarn --frozen-lockfile

      - name: Run Site tests
        working-directory: frontend
        run: yarn test

      - name: Build Gatsby output
        working-directory: frontend
        run: yarn build
        env:
          CONTENTFUL_DELIVERY_API_KEY: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          SITE_URL: ${{ secrets.WEBSITE_URL }}

      - name: Copy settings file to Gatsby output
        working-directory: frontend
        run: cp staticwebapp.config.json public/

      - name: Archive Gatsby output
        uses: actions/upload-artifact@v2
        with:
          name: gatsby-frontend-output
          path: frontend/public

  publish:
    name: Publish the App
    runs-on: ubuntu-latest
    needs: [ api, frontend ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Download Gatsby output
        uses: actions/download-artifact@v2
        with:
          name: gatsby-frontend-output
          path: www

      - name: Deploy Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          action: "upload"
          api_location: "api"
          app_location: "www"
          skip_app_build: true